gptscript-ai/go-gptscript

exec.go
exec_test.go

The Go SDK handled stdout and stderr differently from the other SDKs. This change bring the Go SDK into sync.

fix: update SDK to be consistent with the other SDKs

---

README.md
client.go
client_test.go
opts.go
run.go

This simplification also relieves a deadlock condition when processing stdout.

fix: simplify event processing

---

README.md
client.go
client_test.go
frame.go
opts.go
prompt.go
run.go

A caller must now use `prompt: true` to enable prompting of the user. This explicit opt-in ensures a caller knows they are required to handle the prompt event. If a prompt event occurs when a caller has not explicitly opted-in, then the run fails with an error.

fix: make prompt explicit

---

README.md
gptscript.go
gptscript_test.go
run_test.go

This change also defaults to the SDK server selecting a random available
port.

chore: rename client to gptscript

---

frame.go
gptscript.go
gptscript_test.go
run.go
run_test.go
tool.go

The "source of truth" of how to stringify a tool should be gptscript. This well simplify the maintenance of the SDK.

chore: remove ToString method for tools

---

README.md
gptscript.go
opts.go
run_test.go

Setting the environment at the global level will replace the environment variables from the system. Not specifying any environment will use os.Environ()

feat: add the option to set the environment at the global level

---

README.md
gptscript.go
gptscript_test.go
run.go
tool.go

This change also includes change to Text nodes when parsing files for parity with other SDKs.

fix: better error reporting

---

gptscript_test.go
opts.go

Required for https://github.com/gptscript-ai/gptscript/pull/541

fix: correct default model env var name

---

opts.go

Enable users to set credential overrides on `Run`.
e.g.
```go
run, err := g.Run(
ctx,
"./test.gpt",
gptscript.Options{
DisableCache:  true,
IncludeEvents: true,
CredentialOverride: "sys.openai:OPENAI_API_KEY",
},
)
```
```yaml
tools: github.com/gptscript-ai/dalle-image-generation
You are an expert in image generation. Please generate a lion standing proudly in the savannah.
```
Depends on https://github.com/gptscript-ai/gptscript/pull/570
Addresses https://github.com/gptscript-ai/gptscript/issues/553 for `go-gptscript`

enhance: support credential override

---

run.go

In special circumstances, the goroutine might finish before the wait function was set, causing a panic.

fix: set wait function before spinning off goroutine

---

gptscript_test.go

The LLM may decide to call ls or dir multiple times. Ensure that all such calls are confirmed.

fix: ensure that all ls/dir calls are confirmed in test

---

gptscript.go

If the server is disabled, then it is presumably running with some other environment. In this case, we need to ensure that the run passes the environment so all new environment variables (like prompt server) is properly passed with the run.

fix: pass the environment with the run when server is disabled

---

gptscript_test.go
test/acorn-labs-context.gpt
test/global-tools.gpt

The new test exercises the framework's ability to continue chats where a run failed for some reason.

fix: improve the context testing, including adding a new test

---

gptscript_test.go

The knowledge tool isn't actually used in the test, but it is a good example of a large tool, so it is included.

fix: override the knowledge credential in test

---

gptscript.go
opts.go
run.go

If the server URL has a path, then the SDK will implicitly disable the server since the local SDK server cannot have a path.

feat: add server URL and token options

---

credentials.go
go.mod
gptscript.go
gptscript_test.go
opts.go
run.go
run_test.go
test/credential.gpt
test/global-tools.gpt

depends on gptscript-ai/gptscript#846

feat: add credential management

---

frame.go
gptscript_test.go

Additionally add tests to ensure these are captured properly.

fix: capture Usage, ChatResponseCached, and ToolResults

---

gptscript.go

Now, when the GPTSCRIPT_URL is passed, the SDK will use it and not start its own server. Additionally, the SDK will pass this server URL to child SDK calls.

fix: remove the disable server environment variable

---

datasets.go
gptscript.go
gptscript_test.go
opts.go

This PR depends on https://github.com/gptscript-ai/gptscript/pull/869. The tests in this will fail until that is merged.

feat: add dataset functions

---

workspace.go
workspace_test.go

If the workspace ID is not specified, then it will be read from the GPTSCRIPT_WORKSPACE_ID environment variable.

feat: make the workspace ID optional in the workspace API

---

datasets.go
datasets_test.go

depends on: https://github.com/gptscript-ai/gptscript/pull/885
tests will fail until that is merged

chore: add Add Elements method and update for workspace provider

---

datasets.go
datasets_test.go
opts.go

The only test failure on this PR is due to an unrelated bug with credentials. This is ready for review.

chore: update for dataset rewrite

---

workspace.go
workspace_test.go

depends on https://github.com/gptscript-ai/workspace-provider/pull/10

feat: add to workspace fileinfo

---

pkg/daemon/daemon.go

Here is an example of what it looks like to use these functions:
```go
package main
import (
"fmt"
"net/http"
"os"
"github.com/gptscript-ai/go-gptscript/pkg/daemon"
)
func main() {
server, err := daemon.CreateServer()
if err != nil {
fmt.Printf("failed to create server: %v\n", err)
os.Exit(1)
}
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
clientCert := r.TLS.PeerCertificates[0]
fmt.Fprintf(w, "Hello, %s\n", clientCert.Subject.CommonName)
})
if err := daemon.StartServer(server); err != nil {
fmt.Printf("failed to start server: %v\n", err)
os.Exit(1)
}
}
```

enhance: add functions for daemon servers for mTLS

---

workspace.go
workspace_test.go

This new field acts as an optimistic locking for writing to files.

enhance: add latest_revision for writing files to a workspace

---

gptscript.go

for obot-platform/obot#1997
depends on https://github.com/gptscript-ai/gptscript/pull/951

chore: add function for recreate credentials

---

frame.go
gptscript_test.go

Add options to a field to indicate whether this field can be option/select styles.

Enhance: Add ability to do inline prompting to choose oauth/pat
